# Site settings
title: Kaustubh Sridhar
email: ksridhar@seas.upenn.edu
description: > # this means to ignore newlines until "baseurl:"
  Kaustubh Sridhar, my home on the web. Foundations for this home from <a href='https://ashvin.me/''>Ashvin Nair</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kaustubhsridhar.github.io" # the base hostname & protocol for your site
#url: "http://localhost:4000" # the base hostname & protocol for your site
github_username:  kaustubhsridhar

# Build settings
markdown: kramdown

# This will require each of these plugins automatically.
plugins:
  - jekyll-gist
