# Site settings
title: ashvin.me
email: nair.ashvin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ashvin Nair, my home on the web
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ashvin.me" # the base hostname & protocol for your site
#url: "http://localhost:4000" # the base hostname & protocol for your site
github_username:  anair13

# Build settings
markdown: kramdown

# This will require each of these plugins automatically.
plugins:
  - jekyll-gist
